on:
  push:
    tags:
      - dapp-piggybank/*

jobs:
  release-dapp-piggebank-image:
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@main
    with:
      SERVICE_NAME: "dapp-piggybank"
      BUILD_ARGS: |
        build_image=node:16-slim
      DOCKER_FILE_PATH: Dockerfile
    secrets: inherit
